[project]
name = "xega"
version = "0.1.0"
license = "MIT"
description = ""
authors = [
    {name = "Andrew Emil",email = "andrewcemil@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12, <4.0"
dependencies = [
    "matplotlib (>=3.10.3,<4.0.0)",
    "anthropic (>=0.51.0,<0.52.0)",
    "ollama (>=0.4.8,<0.5.0)",
    "openai (>=1.81.0,<2.0.0)",
    "torch (>=2.7.0,<3.0.0)",
    "transformers (>=4.52.2,<5.0.0)",
    "accelerate (>=1.7.0,<2.0.0)",
    "click (>=8.2.1,<9.0.0)",
    "google-genai (>=1.17.0,<2.0.0)",
    "typeguard (>=4.4.2,<5.0.0)",
]
packages = [
    { include = "xega", from = "src" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-asyncio = "^0.24.0"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = [
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
    "slow: marks tests as slow running",
]
log_cli = true
log_cli_level = "INFO"

[tool.poetry.scripts]
xega = "xega.cli.main:main"
